name: Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      METRICS_TOKEN: ${{ secrets.METRICS_TOKEN }}
    steps:
      - name: Check token
        run: |
          if [ -z "$METRICS_TOKEN" ]; then
            echo "SECRET IS EMPTY - fix the secret name/location"
            exit 1
          else
            echo "secret found"
          fi

      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: borhendkhil
          filename: github-metrics.svg
          base: header, activity, community, repositories
          plugin_languages: yes
          plugin_languages_sections: most-used
          config_timezone: Africa/Tunis
